In [53]:
import torch

w_in_hid = torch.Tensor([
	[1, 1, 1],
	[2, 2, 2],
	[2, 2, 2],
	[3, 3, 3],
	[3, 3, 3],
	[3, 3, 3],
	[4, 4, 4],
	[5, 5, 5],
	[5, 5, 5],
	[6, 6, 6],
	[6, 6, 6],
	[6, 6, 6],
]) # hidden vs. inputs, 12, 3
b_in_hid = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

w_hid_out = torch.Tensor([
	[1, 2, 2, 3, 3, 3, 4, 5, 5, 6, 6, 6],
	[1, 2, 2, 3, 3, 3, 4, 5, 5, 6, 6, 6],
]) # outputs, hidden 2, 12
b_hid_out = torch.Tensor([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]])

hidden_neuron__model_id = torch.Tensor([0, 1, 1, 2, 2, 2, 3, 4, 4, 5, 5, 5]).long()
hidden_neuron__model_id = hidden_neuron__model_id[:, None] # 12,1

# print(f"w_in_hid:\n{w_in_hid}{w_in_hid.shape}")
# print(f"w_hid_out:\n{w_hid_out}{w_hid_out.shape}")
# print(f"hidden_neuron__model_id:\n{hidden_neuron__model_id}{hidden_neuron__model_id.shape}")
# self[index[i][j]][j] *= src[i][j] 
# hidden_neuron__model_id = hidden_neuron__model_id.repeat((1,3))

print(torch.zeros(6,1).scatter_add(0, hidden_neuron__model_id, (w_in_hid).sum(-1)[:, None]))
print(torch.zeros(6,1).scatter_add(0, hidden_neuron__model_id, (b_in_hid)[:, None]))
print(torch.zeros(6,1).scatter_add(0, hidden_neuron__model_id, (w_hid_out).sum(0)[:, None]))
print(torch.zeros(6,1).scatter_add(0, hidden_neuron__model_id, (b_hid_out.sum(1))[:, None]))
# print(6**9)
# hidd

tensor([[ 3.],
        [12.],
        [27.],
        [12.],
        [30.],
        [54.]])
tensor([[ 1.],
        [ 5.],
        [15.],
        [ 7.],
        [17.],
        [33.]])
tensor([[ 2.],
        [ 8.],
        [18.],
        [ 8.],
        [20.],
        [36.]])


RuntimeError: Expected index [12, 1] to be smaller than self [6, 1] apart from dimension 0 and to be smaller size than src [6, 1]